# Generated by Django 4.2.7 on 2024-07-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_question_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='modal_content',
        ),
        migrations.RemoveField(
            model_name='modalcontent',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='modalcontent',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
