# Generated by Django 4.2.7 on 2024-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_modalcontent_video_url_alter_modalcontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalcontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
